name: ci

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['22', '24']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      # add your steps here, e.g. lint, test, build etc.
      - name: Typescript typecheck
        run: |
          npm run typecheck

      - name: Linter check
        run: |
          npm run lint

      - name: Prettier Check
        run: |
          npm run format:check

      - name: Test
        run: |
          npm run test

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: reports/jest-*.xml # Path to test results
          reporter: jest-junit # Format of test results
